// <auto-generated />
using System;
using BeltExam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeltExam.Migrations
{
    [DbContext(typeof(BeltExamContext))]
    partial class BeltExamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeltExam.Models.Thing", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatorId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<string>("DurationUnits")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Time");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Tid");

                    b.HasIndex("CreatorId");

                    b.ToTable("Things");
                });

            modelBuilder.Entity("BeltExam.Models.ThingGuest", b =>
                {
                    b.Property<int>("Aid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("GuestId");

                    b.Property<int>("ThingId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Aid");

                    b.HasIndex("GuestId");

                    b.HasIndex("ThingId");

                    b.ToTable("ThingGuests");
                });

            modelBuilder.Entity("BeltExam.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Dob");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Fname")
                        .IsRequired();

                    b.Property<string>("Lname")
                        .IsRequired();

                    b.Property<string>("PwHash");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Uid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeltExam.Models.Thing", b =>
                {
                    b.HasOne("BeltExam.Models.User", "Creator")
                        .WithMany("ThingsCreated")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeltExam.Models.ThingGuest", b =>
                {
                    b.HasOne("BeltExam.Models.User", "Guest")
                        .WithMany("ThingsAttending")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeltExam.Models.Thing", "Thing")
                        .WithMany("ThingGuests")
                        .HasForeignKey("ThingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
